theme: jekyll-theme-slate
title: "Focused Concept Miner (FCM): Interpretable Deep Learning for Text Exploration"
description: Code and example use cases now available! Links below.
github:
  is_project_page: false
